import { component$, useStore } from "@builder.io/qwik";

export const Todos = component$(() => {
    // TODO UN ESTADO PARA GUARDAR LAS TODOS
    // TODO INTERFACE UNA PARA STORE Y UNA TODO 
    // TODO INPUT + BOTON QUE ME CREE TODO EN UNA VARIABLE EN STADO
    // TODO MOSTRAR EL ARRAY
    // TODO COMPONENTE PARA CREAR EL TODO Y QUE RECIBA UNA PROP
    // TODO MIRES TAILWIND COMO LE DAS STYLES A ESTO , COMO SI FUERA UNA LIBRETA
    // TODO CONTEXTO QUE PASE LOS TODOS index
    return <div></div>
});